spring.application.name=shuttermats-backend

# Puerto del servidor
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:shuttermatsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
