spring.application.name=shuttermats-backend

# Puerto del servidor
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shuttermatsdb}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:femcoders}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# La tabla debe existir antes de que data.sql inserte el seed
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
